### ISSUE TITLE
Doors! Why? What? Where? Who? When? How?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/door#1]
# Todo

+ [x] @iteles Send email to Sr. Antonio with Design/Spec/Detail for Two Rear (e-Accessible) Doors
+ [x] @iteles Send email to Sr. Antonio with Design/Spec for "Front Door" https://github.com/dwyl/door/issues/1#issuecomment-426541858
+ [x] @iteles Follow up request for quote for Leisure Room Folding Door. 
+ [ ] Electronics for ALL e-access doors!

## Why?

I cannot _trust_ some random person with the security _my_ house.
There will be a _nice_ laptop and phone `forEach` person in the house.
That means a thief could get a _sizeable_ "score" if there is _any_ weakness (_within reason_) 
in our _external_ doors. There are **_Five_ External Doors**. 

All electronic access (e-access) doors will all have magnetic locks https://github.com/dwyl/door/issues/11 and key-less entry.
We will be writing our own (_relatively basic_) Open Source Software _using_ https://nerves-project.org 
_strong_ encryption: https://github.com/dwyl/phoenix-ecto-encryption-example 
and an append-only log: https://github.com/dwyl/phoenix-ecto-append-only-log-example
to control all the doors on a closed circuit network (_with **no internet** access_).

All access will be **multi-factor auth**. Doors will have (_both_) cameras and RFID/Bluetooth.
When presence is detected via motion detection the camera will capture a photo and analyse the face. Thankfully this is already being worked on: https://github.com/dwyl/door/issues/6
**`if`** the detected face is recognised, we show the _first_ "**green light**". (_a physical **LED** in the door_)

### Why not use an _Existing_ ("3rd Party") System?

Three reasons:
1. ***Insecurity***: All off-the-shelf systems are closed source ("security through obscurity") and _all_ are ***Hackable*** https://github.com/dwyl/door/issues/8
2. ***Cost***: having ***17*** e-access doors at **€300 each** is _silly_. 
**€5,100** +  installation for something that is ***insecure*** by **`default`** seems _absurd_ to me.
3. ***Learning***: Buying something I can (_relatively_) easily assemble from "parts" would result in virtually _zero_ learning and 100% vendor lock-in. 

Considering that I plan to re-use these locks/system in future projects, I feel that the up-front investment of my _time_ is justified. Having our _own_ (_Open Source_) security/access system will also _unlock_ (_excuse the pun_) _many_ other possibilities. 

## What?

An electronic door lock with **_strong_** digital and physical **security** for a **_low_ cost**.
Open Source Software and Hardware that _anyone_ around the world can use and improve.

## Where?

The Braga [**`home`**](https://github.com/dwyl/home) Co-living/Working House! 

## _Who?_ 

Me. I cannot "outsource" or _delegate_ this work to anyone else (_at least not initially_).
The hope/plan is that other community-based housing/living projects will use and improve ("_harden_") the system and in the not too distant future, all locks and security systems will be open source.

## _When?_

Now!

## How?

List and Categorise the Various Types of Door in the Braga Home:

+ [ ] **How _many_** Doors do we need for Braga [**`home`**](https://github.com/dwyl/home)?
+ [ ] **What _types_** of Door do we need?

# _How Many_ Doors are there in the House? `46` (`20 e-access`)

## Basement `14`

+ [ ] Garage (_External_): Electric Roll-up, **`e-access`**.
+ [ ] Garage (_Internal_): Swing, **`e-access`**.
+ [ ] MR Bathroom: Sliding, no access control.
+ [ ] MR Bedroom: Hinged, **`e-access`**.
+ [ ] Studio: Hinged, **`e-access`**.
+ [ ] Server Closet: Hinged, **`e-access`**.
+ [ ] Machine (Heat Pump AKA "Boiler") Room: Sliding ("hidden"), e-access. (Map!)
+ [ ] Bathroom: 
  + [ ] Entrance: No Door @iteles confirmed below.
  + [ ] Toilet x 2
  + [ ] Shower x 2 
+ [ ] **Emergency Exit** (_External_): Wheelchair Accessible, Electric Open/Close, Magnetic, **`e-access`**.
+ [ ] Leisure Room (_Internal_): Hinged, **`e-access`**.
+ [ ] Leisure Room (_External_): Folding, physical lock (key on chain), magnetic lock, **`e-access`**.

## Middle Floor `12`

+ [ ] Front Door (_External_): Hinged. Opens Outward. Magnetic Lock. **`e-access`**.
+ [ ] Library Door: Hinged. Opens inwards. **`e-access`**. ("Hidden Book Case"). ㊙️ 
+ [ ] Bathroom Door: Hinged. Opens Inwards. 
  + [ ] Gents Section: "_Half Swing Door_". Double-Action (Bi-directional) Hinge.
  + [ ] Mens: Hinged. full height. opens inwards. basic latch.
  + [ ] Ladies: same.
+ [ ] Work Room: Sliding. (_Refurbish existing door_)
+ [ ] Work<->Dining: hinged.
+ [ ] Corridor<->Kitchen: Double-Action (Bi-directional) Hinge. Ply + Perspex. Self-closing. No lock. 
+ [ ] Kitchen<->Dining: "saloon" style double-hinged split doors. 
+ [ ] Kitchen (_External_) **Emergency Exit**. Hinged. Opens outward. Self-closing. Magnetic. **`e-access`**.

## 2<sup>nd</sup> Floor `16`

+ [ ] 5 Bedrooms. All identical Doors. (_all that changes is hinge side_). Hinged (obvs). Mag Lock. **`e-access`**. Custom made from Ply & Stainless Steel Sheet. 
+ [ ] 2 x Bathroom. Hinged. Open inwards. Self-closing. push plate. grab handle. Ply Wood + Stainless.
+ [ ] 3 x Toilets. All same: "Painéis Fenólicos". (hinges change sides). Full-hight. Basic Latch. Ideally self-closing. Grab handle.
+ [ ] 6 x Showers. ["Painéis Fenólicos"](https://github.com/dwyl/home/issues/126). Basic Latch (_ideally with "ocupado" or just **red** when in use_)

## Attic Floor `4`

+ [ ] 4 doors all will be **`e-access`**.
The only downside we have with the Attic floor is that there is no POE to that level 
so we need a custom solution for the doors. 💭

**Comment by iteles** [comment]
@nelsonic On your question above, we don't need a door to the basement bathroom, just the shower and toilet stalls.

**Comment by nelsonic** [comment]
@iteles _sweet_! 🍭 
that means we will have ***42*** Doors in the house. 🎉 😉 
[![image](https://user-images.githubusercontent.com/194400/46396026-17455e80-c6e6-11e8-9c4f-f9e765935cc1.png)](https://youtu.be/D6tINlNluuY)
https://youtu.be/D6tINlNluuY

# 2020 Update: 
we converted the attic into useable rooms so now there are `46` doors ... 
not _quite_ as cool as `42`, but still interesting: https://en.wikipedia.org/wiki/46_(number)

**Comment by nelsonic** [comment]
@iteles I sent you the email with the dimensions and details for the _rear_ Emergency Exit / Access Doors:
![emergency-exit-doors-email-1of2](https://user-images.githubusercontent.com/194400/46396810-5e345380-c6e8-11e8-9a62-a847598a948c.png)
![emergency-exit-doors-email-2of2](https://user-images.githubusercontent.com/194400/46396811-5e345380-c6e8-11e8-9fb5-371fdadec1da.png)

Please CC me when you send it to Sr. Antonio. thanks.

**Comment by nelsonic** [comment]
@iteles _same_ for the _front_ door: 
![braga-front-door-design-email](https://user-images.githubusercontent.com/194400/46396989-e155a980-c6e8-11e8-94cd-b0aca4901806.png)

(_please + thank you!_) ✨

**Comment by nelsonic** [comment]
On Wednesday 3rd October @iteles sent 2 separate emails to Sr. Antonio 
with details of the two Types of External door: 
![image](https://user-images.githubusercontent.com/194400/46551956-11f83780-c8d1-11e8-88b0-2b3345671f74.png)

Yesterday 4th October we spent 3h walking around the house with "Chico" (the carpenter) 
clarifying the spec for all the _internal_ doors. 

I feel the "doors" issue is "on track" so I'm _decreasing_ the priority from `P1` to `P2`.
Still important but not much _we_ can do to move the process forward.

The _next_ action (_already added to the main task/todo list above_) is to start working on the electronics.
In order to get a start on that, we need to finish: https://github.com/dwyl/phoenix-ecto-append-only-log-example

**Comment by stefek99** [comment]
General observation from a keyboard jockey.

Home security is a generic problem, that applies to homes (in general).

When building the **home**, dealing with `X Y Z etc` it is not unreasonable to prioritize and focus on the areas that you know best.

Taking some ready, off the shelf components is a sensible balance. These guys are building some security products:
* https://thisweekinstartups.com/alex-pachikov-sunflower-labs-satya-patel-homebrew/
* https://thisweekinstartups.com/james-siminoff-ring/

And probably 100+ other companies in the space, maybe there are a few who are doing open hardware: https://www.google.co.uk/search?q=open+hardware+home+security

---

Maybe simplify? Only the outside doors to be secure? People inside the house by definition are trusted... Is there really need fo granular access?

Maybe negotiate and bargain, get a massive discount? 

My genuine _(and blatantly honest observation)_ this is geek porn. Unless this is dogfooding and you want to branch off into security solutions...

I'm honestly thinking it's a bigger problem, much more involved that just door. It includes access cards, and logging, and managements software, everything.

**#keyboardjockey**

**Comment by nelsonic** [comment]
@stefek99 we _appreciate_ your enthusiasm for this project and feedback on this issue. ✨ 
We _agree_ that home security is a "**_generic_ problem**" and as such there are _several_ 
companies/teams attempting to _solve_ the it. 

## "_it's a bigger problem, much more involved than just a door_"

_Agreed_.
The name of this repository is _deliberately_ brief as is that of ["home"](https://github.com/dwyl/home) where the doors will be used.
We don't want anyone thinking that we are "overly ambitious" or "grandiose" with our aims.

> Naming the repo something like "**most-secure-home-door-in-the-world**" would be _naive_ at best.

We are _well_ aware that the hardware/software involved in securing the house will need to be "_sophisticated_" to stand _any_ chance of avoiding compromise. This is a challenge we _relish_ not _shirk_. 


## "_it is not unreasonable to prioritize and focus on the areas that you know best._"

Again, we _agree_ that sticking to what we "know best" is **_excellent_ advice**. We _are_ prioritising! ✅ 

What you (_and most other people_) may not realise is that **`before`** we decided to start our little "Web App" company we did "technology risk consulting" (_AKA "**pen-testing**"_) for some of the most high security companies in the world including [DTC](https://en.wikipedia.org/wiki/Diamond_Trading_Company), [LSEG](https://en.wikipedia.org/wiki/London_Stock_Exchange), several Banks and others I can't _mention_. 🙊 
The security of the companies we have tested _vastly_ exceeds that of a typical "house".
We are going to _implement_ security that matches our needs. 
Initially this will _only_ be RFID/NFC based access control. But _before_ we open to the "_public_" we will have a system to rival those used at Gates/Bezos personal residence. 

We don't like to talk about our infosec knowledge/experience much because the _one_ thing we do know about security is that there is _infinitely_ more to learn/know than any _one_ of us could possibly hope to explore. 

We will be _deferring_ to the experience/expertise of _several_ friends who are world-class experts on infosec (_including people who have written core security code for Nest, Tesla, Apple and Casinos_); two of them have offered to visit the house over the next few months to help with this. ✈️ 

# Who _Can_ We/You Trust?

> "_Maybe simplify? Only the outside doors to be secure? People inside the house by definition are trusted... Is there really need fo granular access?_"

People on the ***inside*** of the house are (_only_) **_partially_ trusted**; there are always _levels_ of trust.
I trust people in the house not poison my food or spike my drinks but that does not _automatically_ mean I give them access to my OTP generator for online banking ... 

There will be _multiple_ levels of access `@home`; more on these _later_.
Suffice to say that the https://en.wikipedia.org/wiki/Principle_of_least_privilege will be used.

Being "_blasé_" about security and blanket-trusting everyone is _exactly_ what we will be avoiding. 

# Hardware? 

We will be using open source hardware and components to build the security system(s) of the house.

We have already purchased the ICs and discrete electronics components  for the system.
_Assembly_ of these components and writing the code to control them is _not_ our current focus until the Physical Doors have been manufactured/delivered (_hence this issue_).
We are _managing_ our time as effectively as possible; there are _many_ other things we need to focus on _before_ writing a _line_ of "production" code for the security systems. 

# Off the shelf ... ?

_Most_ off-the-shelf door entry systems are closed source which rules them out immediately.

You name a "startup" that has created a home security system and I will point to their most recent security flaw in the _popular_ press. Let's not even go into exploits available on the "dark web"... 🙊 

## **`@ring`**...? 
+ https://www.digitaltrends.com/home/ring-video-doorbell-security-exploit/
+ https://www.forbes.com/sites/aarontilley/2017/03/22/this-smart-doorbell-was-accidentally-sending-data-to-china-until-people-started-freaking-out/

## Sunflower Labs?

https://sunflower-labs.com is _vapourware_ and a _terrible_ idea. 
![image](https://user-images.githubusercontent.com/194400/46961979-e0822780-d099-11e8-8e0f-9c20c2bf2d8c.png)
An attacker with a paintball gun can _silently_ "take out" the drone with a single shot. 
As a keen drone enthusiast I know exactly how vulnerable quadcopter are to even the slightest prop disturbance. Using a drone to "protect" one's home is like wearing a bullet proof vest and _no trousers_ in a war zone what area of the body is the enemy is going to ["target"](https://www.reddit.com/r/southpark/comments/5mnaj5/you_dont_shoot_a_guy_in_the_dickthats_not_cool)...?

#  "_a massive discount?_"

I would sooner _not open_ the house than get a "massive discount" from anyone for this,
that would be the _single_ biggest "false economy" _imaginable_.

We are paying _full_ price for all components from _trusted_ suppliers.
We have done several factory visits to the Door manufacturer's facilities and are going to be _heavily_ customising the "blanks" that they are making for us according to our specifications.

We aren't using _any_ "off-the-shelf" CCTV or lock products because they all require internet access.
We aren't using a _single_ piece of hardware from "TP Link" or "Huawei" for the _internal_ network.


# Software?

From our research we have not found a project on GitHub/GitLab that even _begins_ to match our needs. 

Having written a decent amount of embedded system and micro-controller code in C/C++, I feel _undaunted_ by the task of writing a few hundred lines of RFID-checking code against a database and using a Beaglebone Green IC to run the system. 

We expect our security systems to _evolve_ quite quickly over the next few months. 
We _must_ maintain the flexibility to iterate _fast_ without having to _wait_ months for some 3rd party to release a "patch" when someone discovers an attack vector. 

> ***Off-the-record***: we expect _other_ houses/organisations/communities to be using our security system within the next year. We will _not_ be charging for any of it. To succeed it _must_ be open and freely and available to _everyone_.

**Comment by stefek99** [comment]
**TLDR:** I read your reply in full.

**TLDR:** Too long didn't reply 😎

So many threads, points, observations.

While totally appreciate your points and unique situation (not everyone is a pentester) I'll remain loyal to my initial assessment - custom security is not required for MVP.

About other organizations - https://wiki.hackerspaces.org/hackbase - worth checking how they manage access. 

You seem very well organized, applying for permits and permissions is badass amazing. **Full trust and full support!**

**Comment by iteles** [comment]
For anyone interested in physical access security and how ridiculously simple it is to get into most doors (including e-access doors), this is a _fascinating_ video about it (and how to fix the issues): 

https://www.youtube.com/watch?v=rnmcRTnTNC8&feature=youtu.be

![image](https://user-images.githubusercontent.com/4185328/47108280-2af2d800-d243-11e8-867e-7ac63cc02378.png)

**Comment by iteles** [comment]
We went by the factory to speak to the manufacturers and added the following specs to the budget request:
+ Extra laminated glass
+ Magnetic lock from the factory
+ Motorised arm to close _and_ open the door for disabled access (on the front door, we don't need a motor for opening though the door should close automatically)

Waiting for the additional budgets to come in.

**Comment by nelsonic** [comment]
## The Search for the Perfect Door - Deviant Ollam | Shakacon
[![image](https://user-images.githubusercontent.com/194400/47346167-60b11a00-d6a4-11e8-93f9-02906c4d2b20.png)](https://youtu.be/4YYvBLAF4T8)
https://youtu.be/4YYvBLAF4T8

**Comment by nelsonic** [comment]
Bad Doors are *everywhere*: https://youtu.be/yY96hTb8WgI

The “Norman” door.

**Comment by nelsonic** [comment]
I count ~~17~~ **`20`** doors in the house that need electronic access.
For the 13 _internal_ doors we will be using a "fail secure" electric strike: https://github.com/dwyl/door/issues/17

**Comment by nelsonic** [comment]
The Electronic Access System is being built in: https://github.com/dwyl/smart-home-security-system/issues/1 🚪
