### ISSUE TITLE
Magnetic Internal Doors (Chico)

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/door#14]
For _everyone's_ security, privacy and peace of mind, the room doors will all have magnetic locks. 🔐 

# Todo

+ [ ] investigate magnetic lock options for the _internal_ doors. 
  + [ ] They don't need to be as strong as the _external_ doors (_which are "maximum strength"_).
  + [ ] Ideally an "in-door" lock would be found. (_Chico promised to send us a link/quote, see below_)

@iteles on Thursday 4<sup>th</sup> October we did our "walk through" with Chico.
He agreed to send us a quote for the magnetic locks for the _internal_ doors.
By tomorrow it will have been 3 weeks since he made this commitment (_to send us a single price..._)
If you have time this morning, please either send him a "follow up" email 
or share his email address with me and I will send him the email from the "shared" email account.

Thanks! ✨

**Comment by iteles** [comment]
When I called him yesterday to sort out the window things, he said:
+ €35 for the 3 'mola' hinges 
+ €270 for a magnetic lock

However, he said it was "battery operated and comes with 2 cards", so I think he has the wrong thing.

I asked him to send us the specs.

**Comment by nelsonic** [comment]
@iteles thanks for following up. 👍 
just need to know if I need to _order_ the Mag Locks from a different supplier and integrate them myself.
